export default {
  colors: {
    "activityBar.background": "#171520",
    "activityBar.dropBackground": "#34294f66",
    "activityBar.foreground": "#ffffffcc",
    "activityBarBadge.background": "#f97e72",
    "activityBarBadge.foreground": "#2a2139",
    "badge.background": "#2a2139",
    "badge.foreground": "#ffffff",
    "breadcrumbPicker.background": "#232530",
    "button.background": "#2a2139",
    "debugToolBar.background": "#241b2f",
    "diffEditor.insertedTextBackground": "#0beb9916",
    "diffEditor.removedTextBackground": "#fe445016",
    "dropdown.background": "#232530",
    "dropdown.listBackground": "#2a2139",
    "editor.background": "#262335",
    "editor.findMatchBackground": "#34294f59",
    "editor.findMatchHighlightBackground": "#34294f33",
    "editor.findRangeHighlightBackground": "#34294f1a",
    "editor.hoverHighlightBackground": "#463465",
    "editor.lineHighlightBackground": "#34294f66",
    "editor.rangeHighlightBackground": "#49549539",
    "editor.selectionBackground": "#ffffff36",
    "editor.selectionHighlightBackground": "#ffffff36",
    "editor.wordHighlightBackground": "#34294f88",
    "editor.wordHighlightStrongBackground": "#34294f88",
    "editorBracketMatch.background": "#34294f66",
    "editorBracketMatch.border": "#495495",
    "editorCodeLens.foreground": "#ffffff7c",
    "editorCursor.background": "#241b2f",
    "editorCursor.foreground": "#f97e72",
    "editorError.foreground": "#fe4450",
    "editorGroup.border": "#495495",
    "editorGroup.dropBackground": "#34294f4a",
    "editorGroupHeader.tabsBackground": "#241b2f",
    "editorGutter.addedBackground": "#206d4bd6",
    "editorGutter.deletedBackground": "#fa2e46a4",
    "editorGutter.modifiedBackground": "#495495af",
    "editorIndentGuide.activeBackground": "#2a2139",
    "editorIndentGuide.background": "#49549539",
    "editorLineNumber.activeForeground": "#ffffffcc",
    "editorLineNumber.foreground": "#ffffff73",
    "editorOverviewRuler.addedForeground": "#09f7a099",
    "editorOverviewRuler.border": "#34294fb3",
    "editorOverviewRuler.deletedForeground": "#fe445099",
    "editorOverviewRuler.errorForeground": "#fe4450dd",
    "editorOverviewRuler.findMatchForeground": "#34294f",
    "editorOverviewRuler.modifiedForeground": "#49549599",
    "editorOverviewRuler.warningForeground": "#72f1b8cc",
    "editorRuler.foreground": "#34294f33",
    "editorSuggestWidget.highlightForeground": "#f97e72",
    "editorSuggestWidget.selectedBackground": "#ffffff36",
    "editorWarning.foreground": "#72f1b8cc",
    "editorWidget.background": "#372d4b",
    "editorWidget.border": "#ffffff22",
    "editorWidget.resizeBorder": "#ffffff44",
    errorForeground: "#fe4450",
    "extensionButton.prominentBackground": "#f97e72",
    "extensionButton.prominentHoverBackground": "#ff7edb",
    focusBorder: "#1f212b",
    foreground: "#ffffff",
    "gitDecoration.addedResourceForeground": "#72f1b8cc",
    "gitDecoration.deletedResourceForeground": "#fe4450",
    "gitDecoration.ignoredResourceForeground": "#ffffff59",
    "gitDecoration.modifiedResourceForeground": "#b893ceee",
    "gitDecoration.untrackedResourceForeground": "#72f1b8",
    "input.background": "#2a2139",
    "inputOption.activeBorder": "#ff7edb99",
    "inputValidation.errorBackground": "#fe445080",
    "inputValidation.errorBorder": "#fe445000",
    "list.activeSelectionBackground": "#ffffff36",
    "list.activeSelectionForeground": "#ffffff",
    "list.dropBackground": "#34294f66",
    "list.errorForeground": "#fe4450e6",
    "list.focusBackground": "#2a213999",
    "list.focusForeground": "#ffffff",
    "list.highlightForeground": "#f97e72",
    "list.hoverBackground": "#2a213999",
    "list.hoverForeground": "#ffffff",
    "list.inactiveFocusBackground": "#2a213999",
    "list.inactiveSelectionBackground": "#34294f66",
    "list.inactiveSelectionForeground": "#ffffff",
    "list.warningForeground": "#72f1b8bb",
    "menu.background": "#463465",
    "panelTitle.activeBorder": "#f97e72",
    "peekView.border": "#495495",
    "peekViewEditor.background": "#232530",
    "peekViewEditor.matchHighlightBackground": "#34294f59",
    "peekViewResult.background": "#232530",
    "peekViewResult.matchHighlightBackground": "#34294f59",
    "peekViewResult.selectionBackground": "#2a213980",
    "peekViewTitle.background": "#232530",
    "pickerGroup.foreground": "#f97e72ea",
    "progressBar.background": "#f97e72",
    "scrollbar.shadow": "#2a2139",
    "scrollbarSlider.activeBackground": "#9d8bca20",
    "scrollbarSlider.background": "#9d8bca30",
    "scrollbarSlider.hoverBackground": "#9d8bca50",
    "selection.background": "#ffffff36",
    "sideBar.background": "#241b2f",
    "sideBar.dropBackground": "#34294f4c",
    "sideBar.foreground": "#ffffff99",
    "sideBarSectionHeader.background": "#241b2f",
    "sideBarSectionHeader.foreground": "#ffffffca",
    "statusBar.background": "#241b2f",
    "statusBar.debuggingBackground": "#f97e72",
    "statusBar.debuggingForeground": "#08080f",
    "statusBar.foreground": "#ffffff80",
    "statusBar.noFolderBackground": "#241b2f",
    "statusBarItem.hoverBackground": "#2a2139",
    "statusBarItem.prominentBackground": "#2a2139",
    "statusBarItem.prominentHoverBackground": "#34294f",
    "tab.activeBorder": "#880088",
    "tab.border": "#241b2f00",
    "tab.inactiveBackground": "#262335",
    "terminal.ansiBlue": "#03edf9",
    "terminal.ansiBrightBlue": "#03edf9",
    "terminal.ansiBrightCyan": "#03edf9",
    "terminal.ansiBrightGreen": "#72f1b8",
    "terminal.ansiBrightMagenta": "#ff7edb",
    "terminal.ansiBrightRed": "#fe4450",
    "terminal.ansiBrightYellow": "#fede5d",
    "terminal.ansiCyan": "#03edf9",
    "terminal.ansiGreen": "#72f1b8",
    "terminal.ansiMagenta": "#ff7edb",
    "terminal.ansiRed": "#fe4450",
    "terminal.ansiYellow": "#f97e72",
    "terminal.foreground": "#ffffff",
    "terminal.selectionBackground": "#34294f4d",
    "terminalCursor.background": "#ffffff",
    "terminalCursor.foreground": "#03edf9",
    "textLink.activeForeground": "#ff7edb",
    "textLink.foreground": "#f97e72",
    "titleBar.activeBackground": "#241b2f",
    "titleBar.inactiveBackground": "#241b2f",
    "walkThrough.embeddedEditorBackground": "#232530",
    "widget.shadow": "#2a2139",
  },
  rules: [
    { token: "comment", foreground: "#495495", background: undefined, fontStyle: "italic" },
    { token: "string.quoted", foreground: "#ff8b39", background: undefined, fontStyle: undefined },
    {
      token: "string.template",
      foreground: "#ff8b39",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "punctuation.definition.string",
      foreground: "#ff8b39",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "string.template meta.embedded.line",
      foreground: "#b6b1b1",
      background: undefined,
      fontStyle: undefined,
    },
    { token: "variable", foreground: "#ff7edb", background: undefined, fontStyle: undefined },
    {
      token: "entity.name.variable",
      foreground: "#ff7edb",
      background: undefined,
      fontStyle: undefined,
    },
    { token: "variable.language", foreground: "#fe4450", background: undefined, fontStyle: "bold" },
    {
      token: "variable.parameter",
      foreground: undefined,
      background: undefined,
      fontStyle: "italic",
    },
    { token: "storage.type", foreground: "#fede5d", background: undefined, fontStyle: undefined },
    {
      token: "storage.modifier",
      foreground: "#fede5d",
      background: undefined,
      fontStyle: undefined,
    },
    { token: "constant", foreground: "#f97e72", background: undefined, fontStyle: undefined },
    { token: "string.regexp", foreground: "#f97e72", background: undefined, fontStyle: undefined },
    {
      token: "constant.numeric",
      foreground: "#f97e72",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "constant.language",
      foreground: "#f97e72",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "constant.character.escape",
      foreground: "#36f9f6",
      background: undefined,
      fontStyle: undefined,
    },
    { token: "entity.name", foreground: "#fe4450", background: undefined, fontStyle: undefined },
    {
      token: "entity.name.tag",
      foreground: "#72f1b8",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "punctuation.definition.tag",
      foreground: "#36f9f6",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "entity.other.attribute-name",
      foreground: "#fede5d",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "entity.other.attribute-name.html",
      foreground: "#fede5d",
      background: undefined,
      fontStyle: "italic",
    },
    {
      token: "entity.name.type",
      foreground: "#fe4450",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "meta.attribute.class.html",
      foreground: "#fe4450",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "entity.other.inherited-class",
      foreground: "#FF0000",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "entity.name.function",
      foreground: "#36f9f6",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "variable.function",
      foreground: "#36f9f6",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "keyword.control.export.js",
      foreground: "#72f1b8",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "keyword.control.import.js",
      foreground: "#72f1b8",
      background: undefined,
      fontStyle: undefined,
    },
    { token: "keyword", foreground: "#fede5d", background: undefined, fontStyle: undefined },
    {
      token: "keyword.control",
      foreground: "#fede5d",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "keyword.operator",
      foreground: "#fede5d",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "keyword.operator.new",
      foreground: "#fede5d",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "keyword.operator.expression",
      foreground: "#fede5d",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "keyword.operator.logical",
      foreground: "#fede5d",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "keyword.other.unit",
      foreground: "#f97e72",
      background: undefined,
      fontStyle: undefined,
    },
    { token: "support", foreground: "#fe4450", background: undefined, fontStyle: undefined },
    {
      token: "support.function",
      foreground: "#36f9f6",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "support.variable",
      foreground: "#ff7edb",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "meta.object-literal.key",
      foreground: "#ff7edb",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "support.type.property-name",
      foreground: "#ff7edb",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "punctuation.separator.key-value",
      foreground: "#b6b1b1",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "punctuation.section.embedded",
      foreground: "#fede5d",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "punctuation.definition.template-expression.begin",
      foreground: "#72f1b8",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "punctuation.definition.template-expression.end",
      foreground: "#72f1b8",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "support.type.property-name.css",
      foreground: "#72f1b8",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "support.type.property-name.json",
      foreground: "#72f1b8",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "switch-block.expr.js",
      foreground: "#72f1b8",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "variable.other.constant.property.js",
      foreground: "#2ee2fa",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "variable.other.property.js",
      foreground: "#2ee2fa",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "constant.other.color",
      foreground: "#f97e72",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "support.constant.font-name",
      foreground: "#f97e72",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "entity.other.attribute-name.id",
      foreground: "#36f9f6",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "entity.other.attribute-name.pseudo-element",
      foreground: "#FF0000",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "entity.other.attribute-name.pseudo-class",
      foreground: "#FF0000",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "support.function.misc.css",
      foreground: "#fe4450",
      background: undefined,
      fontStyle: undefined,
    },
    { token: "markup.heading", foreground: "#ff7edb", background: undefined, fontStyle: undefined },
    {
      token: "entity.name.section",
      foreground: "#ff7edb",
      background: undefined,
      fontStyle: undefined,
    },
    { token: "text.html", foreground: "#ffffffee", background: undefined, fontStyle: undefined },
    {
      token: "keyword.operator.assignment",
      foreground: "#ffffffee",
      background: undefined,
      fontStyle: undefined,
    },
    { token: "markup.quote", foreground: "#b6b1b1cc", background: undefined, fontStyle: "italic" },
    {
      token: "beginning.punctuation.definition.list",
      foreground: "#ff7edb",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "markup.underline.link",
      foreground: "#FF0000",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "string.other.link.description",
      foreground: "#f97e72",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "meta.function-call.generic.python",
      foreground: "#36f9f6",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "storage.type.cs",
      foreground: "#fe4450",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "entity.name.variable.local.cs",
      foreground: "#ff7edb",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "entity.name.variable.field.cs",
      foreground: "#ff7edb",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "entity.name.variable.property.cs",
      foreground: "#ff7edb",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "source.cpp keyword.operator",
      foreground: "#fede5d",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "source.elixir support.type.elixir",
      foreground: "#36f9f6",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "source.elixir meta.module.elixir entity.name.class.elixir",
      foreground: "#36f9f6",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "source.elixir entity.name.function",
      foreground: "#72f1b8",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "source.elixir constant.other.symbol.elixir",
      foreground: "#36f9f6",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "source.elixir constant.other.keywords.elixir",
      foreground: "#36f9f6",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "source.elixir punctuation.definition.string",
      foreground: "#72f1b8",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "source.elixir variable.other.readwrite.module.elixir",
      foreground: "#72f1b8",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token:
        "source.elixir variable.other.readwrite.module.elixir punctuation.definition.variable.elixir",
      foreground: "#72f1b8",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "source.elixir .punctuation.binary.elixir",
      foreground: "#ff7edb",
      background: undefined,
      fontStyle: "italic",
    },
    {
      token: "token.info-token",
      foreground: "#6796e6",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "token.warn-token",
      foreground: "#cd9731",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "token.error-token",
      foreground: "#f44747",
      background: undefined,
      fontStyle: undefined,
    },
    {
      token: "token.debug-token",
      foreground: "#b267e6",
      background: undefined,
      fontStyle: undefined,
    },
    { token: "emphasis", foreground: undefined, background: undefined, fontStyle: "italic" },
    { token: "comment", foreground: undefined, background: undefined, fontStyle: "italic" },
    {
      token: "entity.other.attribute-name",
      foreground: undefined,
      background: undefined,
      fontStyle: "italic",
    },
    {
      token: "entity.other.attribute-name.html",
      foreground: undefined,
      background: undefined,
      fontStyle: "italic",
    },
    {
      token: "entity.other.attribute-name.tag.jade",
      foreground: undefined,
      background: undefined,
      fontStyle: "italic",
    },
    {
      token: "entity.other.attribute-name.tag.pug",
      foreground: undefined,
      background: undefined,
      fontStyle: "italic",
    },
    { token: "markup.italic", foreground: undefined, background: undefined, fontStyle: "italic" },
    { token: "variable.language", foreground: undefined, background: undefined, fontStyle: "" },
  ],
  type: "dark",
  base: "vs-dark",
  inherit: true,
};
