export default {
  name: "SynthWave 84",
  base: "vs-dark",
  inherit: true,
  colors: {
    focusBorder: "#1f212b",
    "editor.foreground": "#ffffff",
    "widget.shadow": "#2a2139",
    "selection.background": "#ffffff36",
    errorForeground: "#fe4450",
    "textLink.activeForeground": "#ff7edb",
    "textLink.foreground": "#f97e72",
    "button.background": "#2a2139",
    "dropdown.background": "#232530",
    "dropdown.listBackground": "#2a2139",
    "input.background": "#2a2139",
    "inputOption.activeBorder": "#ff7edb99",
    "inputValidation.errorBackground": "#fe445080",
    "inputValidation.errorBorder": "#fe445000",
    "scrollbar.shadow": "#2a2139",
    "scrollbarSlider.activeBackground": "#9d8bca20",
    "scrollbarSlider.background": "#9d8bca30",
    "scrollbarSlider.hoverBackground": "#9d8bca50",
    "badge.foreground": "#ffffff",
    "badge.background": "#2a2139",
    "progressBar.background": "#f97e72",
    "list.activeSelectionBackground": "#ffffff36",
    "list.activeSelectionForeground": "#ffffff",
    "list.dropBackground": "#34294f66",
    "list.focusBackground": "#2a213999",
    "list.focusForeground": "#ffffff",
    "list.highlightForeground": "#f97e72",
    "list.hoverBackground": "#2a213999",
    "list.hoverForeground": "#ffffff",
    "list.inactiveSelectionBackground": "#34294f66",
    "list.inactiveSelectionForeground": "#ffffff",
    "list.inactiveFocusBackground": "#2a213999",
    "list.errorForeground": "#fe4450E6",
    "list.warningForeground": "#72f1b8bb",
    "activityBar.background": "#171520",
    "activityBar.dropBackground": "#34294f66",
    "activityBar.foreground": "#ffffffCC",
    "activityBarBadge.background": "#f97e72",
    "activityBarBadge.foreground": "#2a2139",
    "sideBar.background": "#241b2f",
    "sideBar.foreground": "#ffffff99",
    "sideBar.dropBackground": "#34294f4c",
    "sideBarSectionHeader.background": "#241b2f",
    "sideBarSectionHeader.foreground": "#ffffffca",
    "menu.background": "#463465",
    "editorGroup.border": "#495495",
    "editorGroup.dropBackground": "#34294f4a",
    "editorGroupHeader.tabsBackground": "#241b2f",
    "tab.border": "#241b2f00",
    "tab.activeBorder": "#880088",
    "tab.inactiveBackground": "#262335",
    "editor.background": "#262335",
    "editorLineNumber.foreground": "#ffffff73",
    "editorLineNumber.activeForeground": "#ffffffcc",
    "editorCursor.background": "#241b2f",
    "editorCursor.foreground": "#f97e72",
    "editor.selectionBackground": "#ffffff36",
    "editor.selectionHighlightBackground": "#ffffff36",
    "editor.wordHighlightBackground": "#34294f88",
    "editor.wordHighlightStrongBackground": "#34294f88",
    "editor.findMatchBackground": "#34294f59",
    "editor.findMatchHighlightBackground": "#34294f33",
    "editor.findRangeHighlightBackground": "#34294f1a",
    "editor.hoverHighlightBackground": "#463465",
    "editor.lineHighlightBackground": "#262335", // original: #34294f66
    "editor.rangeHighlightBackground": "#49549539",
    "editorIndentGuide.background": "#49549539",
    "editorIndentGuide.activeBackground": "#2a2139",
    "editorRuler.foreground": "#34294f33",
    "editorCodeLens.foreground": "#ffffff7c",
    "editorBracketMatch.background": "#34294f66",
    "editorBracketMatch.border": "#495495",
    "editorOverviewRuler.border": "#34294fb3",
    "editorOverviewRuler.findMatchForeground": "#34294f",
    "editorOverviewRuler.modifiedForeground": "#49549599",
    "editorOverviewRuler.addedForeground": "#09f7a099",
    "editorOverviewRuler.deletedForeground": "#fe445099",
    "editorOverviewRuler.errorForeground": "#fe4450dd",
    "editorOverviewRuler.warningForeground": "#72f1b8cc",
    "editorError.foreground": "#fe4450",
    "editorWarning.foreground": "#72f1b8cc",
    "editorGutter.modifiedBackground": "#495495af",
    "editorGutter.addedBackground": "#206d4bd6",
    "editorGutter.deletedBackground": "#fa2e46a4",
    "diffEditor.insertedTextBackground": "#0beb9916",
    "diffEditor.removedTextBackground": "#fe445016",
    "editorWidget.background": "#372d4b",
    "editorWidget.border": "#ffffff22",
    "editorWidget.resizeBorder": "#ffffff44",
    "editorSuggestWidget.highlightForeground": "#f97e72",
    "editorSuggestWidget.selectedBackground": "#ffffff36",
    "peekView.border": "#495495",
    "peekViewEditor.background": "#232530",
    "peekViewEditor.matchHighlightBackground": "#34294f59",
    "peekViewResult.background": "#232530",
    "peekViewResult.matchHighlightBackground": "#34294f59",
    "peekViewResult.selectionBackground": "#2a213980",
    "peekViewTitle.background": "#232530",
    "panelTitle.activeBorder": "#f97e72",
    "statusBar.background": "#241b2f",
    "statusBar.foreground": "#ffffff80",
    "statusBar.debuggingBackground": "#f97e72",
    "statusBar.debuggingForeground": "#08080f",
    "statusBar.noFolderBackground": "#241b2f",
    "statusBarItem.hoverBackground": "#2a2139",
    "statusBarItem.prominentBackground": "#2a2139",
    "statusBarItem.prominentHoverBackground": "#34294f",
    "titleBar.activeBackground": "#241b2f",
    "titleBar.inactiveBackground": "#241b2f",
    "extensionButton.prominentBackground": "#f97e72",
    "extensionButton.prominentHoverBackground": "#ff7edb",
    "pickerGroup.foreground": "#f97e72ea",
    "terminal.foreground": "#ffffff",
    "terminal.ansiBlue": "#03edf9",
    "terminal.ansiBrightBlue": "#03edf9",
    "terminal.ansiBrightCyan": "#03edf9",
    "terminal.ansiBrightGreen": "#72f1b8",
    "terminal.ansiBrightMagenta": "#ff7edb",
    "terminal.ansiBrightRed": "#fe4450",
    "terminal.ansiBrightYellow": "#fede5d",
    "terminal.ansiCyan": "#03edf9",
    "terminal.ansiGreen": "#72f1b8",
    "terminal.ansiMagenta": "#ff7edb",
    "terminal.ansiRed": "#fe4450",
    "terminal.ansiYellow": "#f97e72",
    "terminal.selectionBackground": "#34294f4d",
    "terminalCursor.background": "#ffffff",
    "terminalCursor.foreground": "#03edf9",
    "debugToolBar.background": "#241b2f",
    "walkThrough.embeddedEditorBackground": "#232530",
    "gitDecoration.modifiedResourceForeground": "#b893ceee",
    "gitDecoration.deletedResourceForeground": "#fe4450",
    "gitDecoration.addedResourceForeground": "#72f1b8cc",
    "gitDecoration.untrackedResourceForeground": "#72f1b8",
    "gitDecoration.ignoredResourceForeground": "#ffffff59",
    "breadcrumbPicker.background": "#232530",
  },
  rules: [
    { token: "comment", foreground: "#495495", fontStyle: "italic" },
    {
      token: "string.quoted string.template punctuation.definition.string",
      foreground: "#ff8b39",
    },
    { token: "string.template meta.embedded.line", foreground: "#b6b1b1" },
    { token: "variable entity.name.variable", foreground: "#ff7edb" },
    {
      token: "variable.language",
      foreground: "#fe4450",
      fontStyle: "bold",
    },
    { token: "variable.parameter", fontStyle: "italic" },
    { token: "storage.type storage.modifier", foreground: "#fede5d" },
    {
      foreground: "fede5d",
      token: "source.js meta.function.js",
    },
    { token: "constant", foreground: "#f97e72" },
    { token: "string.regexp", foreground: "#f97e72" },
    { token: "constant.numeric", foreground: "#f97e72" },
    { token: "constant.language", foreground: "#f97e72" },
    { token: "constant.character.escape", foreground: "#36f9f6" },
    { token: "entity.name", foreground: "#fe4450" },
    { token: "entity.name.tag", foreground: "#72f1b8" },
    { token: "punctuation.definition.tag", foreground: "#36f9f6" },
    { token: "entity.other.attribute-name", foreground: "#fede5d" },
    {
      token: "entity.other.attribute-name.html",
      foreground: "#fede5d",
      fontStyle: "italic",
    },
    {
      token: "entity.name.type meta.attribute.class.html",
      foreground: "#fe4450",
    },
    { token: "entity.other.inherited-class", foreground: "#dd5500" },
    {
      token: "entity.name.function variable.function",
      foreground: "#36f9f6",
    },
    {
      scope: ["source.js", "meta.function.js", "storage.type.function.js"],
      foreground: "#36f9f6",
    },
    {
      token: "keyword.control.export.js keyword.control.import.js",
      foreground: "#72f1b8",
    },
    { token: "keyword", foreground: "#fede5d" },
    { token: "keyword.control", foreground: "#fede5d" },
    { token: "keyword.operator", foreground: "#fede5d" },
    {
      token: "keyword.operator.new keyword.operator.expression keyword.operator.logical",
      foreground: "#fede5d",
    },
    { token: "keyword.other.unit", foreground: "#f97e72" },
    { token: "support", foreground: "#fe4450" },
    { token: "support.function", foreground: "#36f9f6" },
    { token: "support.variable", foreground: "#ff7edb" },
    {
      token: "meta.object-literal.key support.type.property-name",
      foreground: "#ff7edb",
    },
    { token: "punctuation.separator.key-value", foreground: "#b6b1b1" },
    { token: "punctuation.section.embedded", foreground: "#fede5d" },
    {
      token:
        "punctuation.definition.template-expression.begin punctuation.definition.template-expression.end",
      foreground: "#72f1b8",
    },
    {
      token: "support.type.property-name.css support.type.property-name.json",
      foreground: "#72f1b8",
    },
    { token: "switch-block.expr.js", foreground: "#72f1b8" },
    {
      token: "variable.other.constant.property.js, variable.other.property.js",
      foreground: "#2ee2fa",
    },
    { token: "constant.other.color", foreground: "#f97e72" },
    { token: "support.constant.font-name", foreground: "#f97e72" },
    { token: "entity.other.attribute-name.id", foreground: "#36f9f6" },
    {
      token: "entity.other.attribute-name.pseudo-element entity.other.attribute-name.pseudo-class",
      foreground: "#dd5500",
    },
    { token: "support.function.misc.css", foreground: "#fe4450" },
    { token: "markup.heading entity.name.section", foreground: "#ff7edb" },
    {
      token: "text.html keyword.operator.assignment",
      foreground: "#ffffffee",
    },
    {
      token: "markup.quote",
      foreground: "#b6b1b1cc",
      fontStyle: "italic",
    },
    {
      token: "beginning.punctuation.definition.list",
      foreground: "#ff7edb",
    },
    { token: "markup.underline.link", foreground: "#dd5500" },
    { token: "string.other.link.description", foreground: "#f97e72" },
    { token: "meta.function-call.generic.python", foreground: "#36f9f6" },
    { token: "storage.type.cs", foreground: "#fe4450" },
    { token: "entity.name.variable.local.cs", foreground: "#ff7edb" },
    {
      token: "entity.name.variable.field.cs entity.name.variable.property.cs",
      foreground: "#ff7edb",
    },
    { token: "source.cpp keyword.operator", foreground: "#fede5d" },
    {
      token:
        "source.elixir support.type.elixir source.elixir meta.module.elixir entity.name.class.elixir",
      foreground: "#36f9f6",
    },
    { token: "source.elixir entity.name.function", foreground: "#72f1b8" },
    {
      token:
        "source.elixir constant.other.symbol.elixir source.elixir constant.other.keywords.elixir",
      foreground: "#36f9f6",
    },
    {
      token: "source.elixir punctuation.definition.string",
      foreground: "#72f1b8",
    },
    {
      token:
        "source.elixir variable.other.readwrite.module.elixir source.elixir variable.other.readwrite.module.elixir punctuation.definition.variable.elixir",
      foreground: "#72f1b8",
    },
    {
      token: "source.elixir .punctuation.binary.elixir",
      foreground: "#ff7edb",
      fontStyle: "italic",
    },
  ],
};
