export default [
  // { name: "abap", value: "abap" },
  // { name: "abc", value: "abc" },
  // { name: "actionscript", value: "actionscript" },
  // { name: "ada", value: "ada" },
  // { name: "apache_conf", value: "apache_conf" },
  // { name: "applescript", value: "applescript" },
  // { name: "asciidoc", value: "asciidoc" },
  // { name: "assembly_x86", value: "assembly_x86" },
  // { name: "autohotkey", value: "autohotkey" },
  // { name: "batchfile", value: "batchfile" },
  // { name: "bro", value: "bro" },
  // { name: "c9search", value: "c9search" },
  // { name: "c_cpp", value: "c_cpp" },
  // { name: "cirru", value: "cirru" },
  { name: "clojure", value: "clojure" },
  // { name: "cobol", value: "cobol" },
  // { name: "coffee", value: "coffee" },
  // { name: "coldfusion", value: "coldfusion" },
  // { name: "csharp", value: "csharp" },
  // { name: "csound_document", value: "csound_document" },
  // { name: "csound_orchestra", value: "csound_orchestra" },
  // { name: "csound_score", value: "csound_score" },
  { name: "css", value: "css" },
  // { name: "curly", value: "curly" },
  // { name: "d", value: "d" },
  // { name: "dart", value: "dart" },
  // { name: "diff", value: "diff" },
  // { name: "django", value: "django" },
  // { name: "dockerfile", value: "dockerfile" },
  // { name: "dot", value: "dot" },
  // { name: "drools", value: "drools" },
  // { name: "eiffel", value: "eiffel" },
  // { name: "ejs", value: "ejs" },
  { name: "elixir", value: "elixir" },
  // { name: "elm", value: "elm" },
  // { name: "erlang", value: "erlang" },
  // { name: "forth", value: "forth" },
  // { name: "fortran", value: "fortran" },
  // { name: "ftl", value: "ftl" },
  // { name: "gcode", value: "gcode" },
  // { name: "gherkin", value: "gherkin" },
  // { name: "gitignore", value: "gitignore" },
  // { name: "glsl", value: "glsl" },
  // { name: "gobstones", value: "gobstones" },
  { name: "golang", value: "golang" },
  // { name: "graphqlschema", value: "graphqlschema" },
  // { name: "groovy", value: "groovy" },
  // { name: "haml", value: "haml" },
  // { name: "handlebars", value: "handlebars" },
  { name: "haskell", value: "haskell" },
  // { name: "haskell_cabal", value: "haskell_cabal" },
  // { name: "haxe", value: "haxe" },
  // { name: "hjson", value: "hjson" },
  { name: "html", value: "html" },
  // { name: "html_elixir", value: "html_elixir" },
  // { name: "html_ruby", value: "html_ruby" },
  // { name: "ini", value: "ini" },
  // { name: "io", value: "io" },
  // { name: "jack", value: "jack" },
  // { name: "jade", value: "jade" },
  { name: "java", value: "java" },
  { name: "javascript", value: "javascript" },
  { name: "json", value: "json" },
  // { name: "jsoniq", value: "jsoniq" },
  // { name: "jsp", value: "jsp" },
  // { name: "jssm", value: "jssm" },
  // { name: "jsx", value: "jsx" },
  // { name: "julia", value: "julia" },
  { name: "kotlin", value: "kotlin" },
  // { name: "latex", value: "latex" },
  // { name: "lean", value: "lean" },
  // { name: "less", value: "less" },
  // { name: "liquid", value: "liquid" },
  // { name: "lisp", value: "lisp" },
  // { name: "live_script", value: "live_script" },
  // { name: "livescript", value: "livescript" },
  // { name: "logiql", value: "logiql" },
  // { name: "lsl", value: "lsl" },
  // { name: "lua", value: "lua" },
  // { name: "luapage", value: "luapage" },
  // { name: "lucene", value: "lucene" },
  // { name: "makefile", value: "makefile" },
  // { name: "markdown", value: "markdown" },
  // { name: "mask", value: "mask" },
  // { name: "matlab", value: "matlab" },
  // { name: "mavens_mate_log", value: "mavens_mate_log" },
  // { name: "maze", value: "maze" },
  // { name: "mel", value: "mel" },
  // { name: "mips_assembler", value: "mips_assembler" },
  // { name: "mipsassembler", value: "mipsassembler" },
  // { name: "mushcode", value: "mushcode" },
  // { name: "mysql", value: "mysql" },
  // { name: "nix", value: "nix" },
  // { name: "nsis", value: "nsis" },
  // { name: "objectivec", value: "objectivec" },
  // { name: "ocaml", value: "ocaml" },
  // { name: "pascal", value: "pascal" },
  // { name: "perl", value: "perl" },
  // { name: "pgsql", value: "pgsql" },
  { name: "php", value: "php" },
  // { name: "pig", value: "pig" },
  // { name: "plain_text", value: "plain_text" },
  // { name: "powershell", value: "powershell" },
  // { name: "praat", value: "praat" },
  // { name: "prolog", value: "prolog" },
  // { name: "properties", value: "properties" },
  // { name: "protobuf", value: "protobuf" },
  { name: "python", value: "python" },
  // { name: "r", value: "r" },
  // { name: "razor", value: "razor" },
  // { name: "rdoc", value: "rdoc" },
  // { name: "red", value: "red" },
  // { name: "rhtml", value: "rhtml" },
  // { name: "rst", value: "rst" },
  { name: "ruby", value: "ruby" },
  { name: "rust", value: "rust" },
  // { name: "sass", value: "sass" },
  // { name: "scad", value: "scad" },
  { name: "scala", value: "scala" },
  // { name: "scheme", value: "scheme" },
  // { name: "scss", value: "scss" },
  // { name: "sh", value: "sh" },
  // { name: "sjs", value: "sjs" },
  // { name: "smarty", value: "smarty" },
  // { name: "snippets", value: "snippets" },
  // { name: "soy_template", value: "soy_template" },
  // { name: "space", value: "space" },
  // { name: "sparql", value: "sparql" },
  // { name: "sql", value: "sql" },
  // { name: "sqlserver", value: "sqlserver" },
  // { name: "stylus", value: "stylus" },
  // { name: "svg", value: "svg" },
  { name: "swift", value: "swift" },
  // { name: "swig", value: "swig" },
  // { name: "tcl", value: "tcl" },
  // { name: "tex", value: "tex" },
  // { name: "text", value: "text" },
  // { name: "textile", value: "textile" },
  // { name: "toml", value: "toml" },
  // { name: "tsx", value: "tsx" },
  // { name: "turtle", value: "turtle" },
  // { name: "twig", value: "twig" },
  { name: "typescript", value: "typescript" },
  // { name: "vala", value: "vala" },
  // { name: "vbscript", value: "vbscript" },
  // { name: "velocity", value: "velocity" },
  // { name: "verilog", value: "verilog" },
  // { name: "vhdl", value: "vhdl" },
  // { name: "wollok", value: "wollok" },
  // { name: "xml", value: "xml" },
  // { name: "xquery", value: "xquery" },
  // { name: "yaml", value: "yaml" }
];
